--Dataset: Adidas US Sales Datasets
--Source: https://www.kaggle.com

--*analyse the Adidas US Sales in between 01/2020 and 12/2021*


-- total sales
select SUM(Adidas.dbo.Sales.[Total Sales]) as adidas_total_sales
from Adidas.dbo.Sales

--the avg ordder value
select [Retailer ID],[Total Sales], [Units Sold], ([Total Sales]/[Units Sold] ) as avg_order_value
from Adidas..Sales
where [Units Sold] > 0


--Determine the overall profit margin

select [Retailer ID],[Operating Profit], [Total Sales], [Operating Profit]/[Total Sales] as overall_profit_margin
from Adidas..Sales
where [Total Sales] > 0


--the top-selling products based on units sold.
select [Retailer ID],Retailer,Product, [Units Sold]
from Adidas..Sales
order by [Units Sold] desc


-- revenue generated by each product category
SELECT product, SUM( [Total Sales]) AS total_revenue_per_category
FROM Adidas..Sales
GROUP BY product
ORDER BY total_revenue_per_category DESC;


-- Geographical Analysis
------the reveney per state
select Adidas..Sales.State, SUM([Total Sales]) as total_revenue_per_state
from Adidas..Sales
group by State
order by total_revenue_per_state desc

-- regional trends
SELECT 
    YEAR([Invoice Date]) AS year,
    MONTH([Invoice Date]) AS month,
    State,
    SUM([Total Sales]) AS regional_monthly_sales
FROM Adidas..Sales
GROUP BY YEAR([Invoice Date]), MONTH([Invoice Date]), State
ORDER BY year, month, State 

--Sales Method 
--revenue per sales retailer
select Retailer, sum([Total Sales]) as total_revenue
from Adidas..Sales
group by Retailer
order by total_revenue desc
 
 --revenue per sales methode
 select [Sales Method], sum([Total Sales]) as total_revenue
 from Adidas..Sales
 group by [Sales Method]
 order by total_revenue

 -- profitability by region and product category
 select Region, sum([Total Sales]) as total_sales_per_category,SUM([Operating Profit]) AS total_profit_per_category_region, Product
 from Adidas..Sales
 group by Product,Region
 order by total_profit_per_category_region, total_sales_per_category desc
 